In [3]:
import pandas as pd
import numpy as np
np.random.randn(150).reshape((50,3));

In [4]:
7+8

15

In [5]:
import pandas as pd
import numpy as np

In [92]:
k=pd.DataFrame(np.random.randn(150).reshape((50,3)));

In [93]:
k

           0         1         2
0  -0.707426  0.219924 -0.135498
1  -1.420991 -0.757071  1.303350
2  -0.743845  0.091414  0.304443
3   1.656585  1.599320  1.168198
4  -1.371662  0.131730 -0.563045
5  -2.528132 -1.387927 -1.687678
6   0.576487 -1.565742 -0.292461
7  -0.678988 -0.175047 -0.843291
8   0.505282 -0.404542  0.634397
9   0.021965  0.840554  1.662810
10 -0.276642  1.317030 -0.598513
11  0.946118  2.867409  0.459316
12  0.081226  0.299162 -0.533026
13  0.077880  1.528570 -0.033770
14  0.087146 -1.068192  0.685027
15  0.585727  0.056810 -0.824828
16  2.898903  0.925097  1.915837
17 -0.925602 -0.029634 -1.265946
18 -1.043710  0.032791 -0.360433
19 -1.270543  1.228248  0.124210
20  1.007473 -0.616905 -1.023697
21 -2.456578 -0.906363 -0.288901
22 -0.545592 -1.499812 -0.089958
23  1.411284  0.335008 -1.911956
24 -1.468716 -2.569037  0.896909
25 -0.584318  0.174206  3.028226
26  0.015619 -0.077268 -1.385655
27  1.191175  0.953772  0.354512
28  1.191991  0.095128 -0.590488
29 -1.118067  1.729722  1.204668
30  0.443431 -1.117314 -0.036582
31 -1.480004  1.247244 -0.109951
32 -0.514731  1.455674 -0.688065
33 -0.876742 -0.766922  0.209406
34  0.999265 -0.056820 -0.603960
35  1.218957 -0.437381 -0.101947
36  0.889065 -0.036806  1.267912
37 -1.579665 -1.544169 -1.413230
38 -0.941903  1.614733 -0.315585
39  0.547935  1.233692 -0.384419
40  0.972781  1.039949  1.543776
41 -0.825916  1.942681 -1.849283
42 -0.099794  0.170749 -1.288881
43  0.287042 -0.506104 -0.678657
44  0.441296 -0.099060  0.347198
45 -0.365115 -0.807221 -0.932193
46 -1.787543  1.222139 -0.935932
47 -0.338019 -2.027892  1.155308
48 -1.406451 -0.221610 -2.718018
49  0.494161  0.320213 -0.827758

In [48]:

for i in range(14):
    # for j in range(5):
    
        k=  k.replace(k.iloc[i,0],np.nan)

In [49]:
k

           0         1         2
0        NaN  0.270980  1.687573
1        NaN -0.341689  0.866988
2        NaN  0.501689 -0.666703
3        NaN  0.741854 -2.067728
4        NaN -0.299077 -2.452512
5        NaN  0.608005 -1.190539
6        NaN  0.322498  3.086414
7        NaN  0.687090  0.799296
8        NaN  0.322271  1.546773
9        NaN -0.774622  0.799672
10       NaN  0.402205 -0.243459
11       NaN  0.020949 -0.164337
12       NaN -0.581571 -1.208786
13       NaN  0.115256  1.922143
14  0.091765  0.428241 -0.858772
15 -0.054696  2.007380  0.107490
16  0.288652  0.832567 -0.507965
17 -0.220908 -0.229645  1.684209
18 -0.322385  1.474997 -0.034501
19  1.525100  0.598120 -0.838915
20  0.774785  0.368730  0.171380
21  1.722635 -0.374419  0.722198
22  2.472393  0.435503  1.061459
23  0.887373  2.006799  0.812037
24 -1.424171 -0.870280  0.058297
25 -0.490323  0.925983  0.120369
26 -0.501222  1.535428 -1.409283
27  0.787017 -0.455415  1.369814
28 -1.475195 -1.679859 -1.448932
29  1.112902 -0.109537 -0.261500
30 -0.096553  0.796669  0.364840
31 -2.169390 -0.148541 -0.547193
32 -0.820688  0.415250  0.741441
33 -0.590462 -0.121354 -1.044040
34  0.971552  0.182742  0.022814
35 -0.259488 -1.892343 -1.303312
36  0.936912  0.492828 -0.346970
37  0.126210  0.842273  1.316378
38 -1.253673  1.146065 -0.761661
39 -0.415091 -1.210996 -0.438056
40  0.333247 -0.758408  0.124656
41 -0.340385  0.638143  0.150507
42  1.826399 -0.954583  1.199159
43  0.835668  1.460355  0.129876
44 -0.992402 -0.905073  0.003292
45  1.044798 -0.458899  0.990410
46 -0.229939 -0.279109 -0.550187
47  0.367915 -1.703930  1.512137
48 -0.871607  0.409052  0.975038
49 -0.235378  0.534935 -1.642741

In [39]:
k.replace(k.iloc[3,2],np.nan)

           0         1         2
0   1.437085  0.270980  1.687573
1   1.004918 -0.341689  0.866988
2  -1.369797  0.501689 -0.666703
3   0.578468  0.741854       NaN
4   0.619108 -0.299077 -2.452512
5  -0.327877  0.608005 -1.190539
6  -2.049245  0.322498  3.086414
7   0.000317  0.687090  0.799296
8   2.039825  0.322271  1.546773
9   0.165373 -0.774622  0.799672
10  0.020532  0.402205 -0.243459
11 -1.468542  0.020949 -0.164337
12 -1.186532 -0.581571 -1.208786
13  1.160923  0.115256  1.922143
14  0.091765  0.428241 -0.858772
15 -0.054696  2.007380  0.107490
16  0.288652  0.832567 -0.507965
17 -0.220908 -0.229645  1.684209
18 -0.322385  1.474997 -0.034501
19  1.525100  0.598120 -0.838915
20  0.774785  0.368730  0.171380
21  1.722635 -0.374419  0.722198
22  2.472393  0.435503  1.061459
23  0.887373  2.006799  0.812037
24 -1.424171 -0.870280  0.058297
25 -0.490323  0.925983  0.120369
26 -0.501222  1.535428 -1.409283
27  0.787017 -0.455415  1.369814
28 -1.475195 -1.679859 -1.448932
29  1.112902 -0.109537 -0.261500
30 -0.096553  0.796669  0.364840
31 -2.169390 -0.148541 -0.547193
32 -0.820688  0.415250  0.741441
33 -0.590462 -0.121354 -1.044040
34  0.971552  0.182742  0.022814
35 -0.259488 -1.892343 -1.303312
36  0.936912  0.492828 -0.346970
37  0.126210  0.842273  1.316378
38 -1.253673  1.146065 -0.761661
39 -0.415091 -1.210996 -0.438056
40  0.333247 -0.758408  0.124656
41 -0.340385  0.638143  0.150507
42  1.826399 -0.954583  1.199159
43  0.835668  1.460355  0.129876
44 -0.992402 -0.905073  0.003292
45  1.044798 -0.458899  0.990410
46 -0.229939 -0.279109 -0.550187
47  0.367915 -1.703930  1.512137
48 -0.871607  0.409052  0.975038
49 -0.235378  0.534935 -1.642741

In [50]:
k.isnull().sum()

0    14
1     0
2     0
dtype: int64

In [56]:
k.dropna(axis=1)

           1         2
0   0.270980  1.687573
1  -0.341689  0.866988
2   0.501689 -0.666703
3   0.741854 -2.067728
4  -0.299077 -2.452512
5   0.608005 -1.190539
6   0.322498  3.086414
7   0.687090  0.799296
8   0.322271  1.546773
9  -0.774622  0.799672
10  0.402205 -0.243459
11  0.020949 -0.164337
12 -0.581571 -1.208786
13  0.115256  1.922143
14  0.428241 -0.858772
15  2.007380  0.107490
16  0.832567 -0.507965
17 -0.229645  1.684209
18  1.474997 -0.034501
19  0.598120 -0.838915
20  0.368730  0.171380
21 -0.374419  0.722198
22  0.435503  1.061459
23  2.006799  0.812037
24 -0.870280  0.058297
25  0.925983  0.120369
26  1.535428 -1.409283
27 -0.455415  1.369814
28 -1.679859 -1.448932
29 -0.109537 -0.261500
30  0.796669  0.364840
31 -0.148541 -0.547193
32  0.415250  0.741441
33 -0.121354 -1.044040
34  0.182742  0.022814
35 -1.892343 -1.303312
36  0.492828 -0.346970
37  0.842273  1.316378
38  1.146065 -0.761661
39 -1.210996 -0.438056
40 -0.758408  0.124656
41  0.638143  0.150507
42 -0.954583  1.199159
43  1.460355  0.129876
44 -0.905073  0.003292
45 -0.458899  0.990410
46 -0.279109 -0.550187
47 -1.703930  1.512137
48  0.409052  0.975038
49  0.534935 -1.642741

In [78]:
sum=k.sum(axis=1)
sum

0     1.958553
1     0.525300
2    -0.165014
3    -1.325873
4    -2.751589
5    -0.582534
6     3.408912
7     1.486386
8     1.869044
9     0.025050
10    0.158747
11   -0.143387
12   -1.790357
13    2.037399
14   -0.338765
15    2.060174
16    0.613254
17    1.233656
18    1.118111
19    1.284305
20    1.314895
21    2.070413
22    3.969355
23    3.706209
24   -2.236154
25    0.556029
26   -0.375077
27    1.701416
28   -4.603986
29    0.741866
30    1.064956
31   -2.865124
32    0.336003
33   -1.755856
34    1.177107
35   -3.455143
36    1.082770
37    2.284860
38   -0.869269
39   -2.064143
40   -0.300506
41    0.448265
42    2.070976
43    2.425899
44   -1.894184
45    1.576309
46   -1.059236
47    0.176122
48    0.512483
49   -1.343184
dtype: float64

In [82]:
max=sum.argmax()

In [83]:
max

22

In [85]:
k.drop([22])

           0         1         2
0        NaN  0.270980  1.687573
1        NaN -0.341689  0.866988
2        NaN  0.501689 -0.666703
3        NaN  0.741854 -2.067728
4        NaN -0.299077 -2.452512
5        NaN  0.608005 -1.190539
6        NaN  0.322498  3.086414
7        NaN  0.687090  0.799296
8        NaN  0.322271  1.546773
9        NaN -0.774622  0.799672
10       NaN  0.402205 -0.243459
11       NaN  0.020949 -0.164337
12       NaN -0.581571 -1.208786
13       NaN  0.115256  1.922143
14  0.091765  0.428241 -0.858772
15 -0.054696  2.007380  0.107490
16  0.288652  0.832567 -0.507965
17 -0.220908 -0.229645  1.684209
18 -0.322385  1.474997 -0.034501
19  1.525100  0.598120 -0.838915
20  0.774785  0.368730  0.171380
21  1.722635 -0.374419  0.722198
23  0.887373  2.006799  0.812037
24 -1.424171 -0.870280  0.058297
25 -0.490323  0.925983  0.120369
26 -0.501222  1.535428 -1.409283
27  0.787017 -0.455415  1.369814
28 -1.475195 -1.679859 -1.448932
29  1.112902 -0.109537 -0.261500
30 -0.096553  0.796669  0.364840
31 -2.169390 -0.148541 -0.547193
32 -0.820688  0.415250  0.741441
33 -0.590462 -0.121354 -1.044040
34  0.971552  0.182742  0.022814
35 -0.259488 -1.892343 -1.303312
36  0.936912  0.492828 -0.346970
37  0.126210  0.842273  1.316378
38 -1.253673  1.146065 -0.761661
39 -0.415091 -1.210996 -0.438056
40  0.333247 -0.758408  0.124656
41 -0.340385  0.638143  0.150507
42  1.826399 -0.954583  1.199159
43  0.835668  1.460355  0.129876
44 -0.992402 -0.905073  0.003292
45  1.044798 -0.458899  0.990410
46 -0.229939 -0.279109 -0.550187
47  0.367915 -1.703930  1.512137
48 -0.871607  0.409052  0.975038
49 -0.235378  0.534935 -1.642741

In [86]:
k.sort_values(0)

           0         1         2
31 -2.169390 -0.148541 -0.547193
28 -1.475195 -1.679859 -1.448932
24 -1.424171 -0.870280  0.058297
38 -1.253673  1.146065 -0.761661
44 -0.992402 -0.905073  0.003292
48 -0.871607  0.409052  0.975038
32 -0.820688  0.415250  0.741441
33 -0.590462 -0.121354 -1.044040
26 -0.501222  1.535428 -1.409283
25 -0.490323  0.925983  0.120369
39 -0.415091 -1.210996 -0.438056
41 -0.340385  0.638143  0.150507
18 -0.322385  1.474997 -0.034501
35 -0.259488 -1.892343 -1.303312
49 -0.235378  0.534935 -1.642741
46 -0.229939 -0.279109 -0.550187
17 -0.220908 -0.229645  1.684209
30 -0.096553  0.796669  0.364840
15 -0.054696  2.007380  0.107490
14  0.091765  0.428241 -0.858772
37  0.126210  0.842273  1.316378
16  0.288652  0.832567 -0.507965
40  0.333247 -0.758408  0.124656
47  0.367915 -1.703930  1.512137
20  0.774785  0.368730  0.171380
27  0.787017 -0.455415  1.369814
43  0.835668  1.460355  0.129876
23  0.887373  2.006799  0.812037
36  0.936912  0.492828 -0.346970
34  0.971552  0.182742  0.022814
45  1.044798 -0.458899  0.990410
29  1.112902 -0.109537 -0.261500
19  1.525100  0.598120 -0.838915
21  1.722635 -0.374419  0.722198
42  1.826399 -0.954583  1.199159
22  2.472393  0.435503  1.061459
0        NaN  0.270980  1.687573
1        NaN -0.341689  0.866988
2        NaN  0.501689 -0.666703
3        NaN  0.741854 -2.067728
4        NaN -0.299077 -2.452512
5        NaN  0.608005 -1.190539
6        NaN  0.322498  3.086414
7        NaN  0.687090  0.799296
8        NaN  0.322271  1.546773
9        NaN -0.774622  0.799672
10       NaN  0.402205 -0.243459
11       NaN  0.020949 -0.164337
12       NaN -0.581571 -1.208786
13       NaN  0.115256  1.922143

In [94]:
for i in range(15):
    j=np.random.randint(2);
    i=i+j
    k=k.replace(k.iloc[i,j],np.nan);
k

           0         1         2
0  -0.707426  0.219924 -0.135498
1  -1.420991       NaN  1.303350
2        NaN       NaN  0.304443
3   1.656585  1.599320  1.168198
4  -1.371662       NaN -0.563045
5        NaN       NaN -1.687678
6   0.576487 -1.565742 -0.292461
7  -0.678988       NaN -0.843291
8        NaN       NaN  0.634397
9   0.021965  0.840554  1.662810
10       NaN       NaN -0.598513
11       NaN  2.867409  0.459316
12       NaN  0.299162 -0.533026
13  0.077880  1.528570 -0.033770
14       NaN       NaN  0.685027
15  0.585727  0.056810 -0.824828
16  2.898903  0.925097  1.915837
17 -0.925602 -0.029634 -1.265946
18 -1.043710  0.032791 -0.360433
19 -1.270543  1.228248  0.124210
20  1.007473 -0.616905 -1.023697
21 -2.456578 -0.906363 -0.288901
22 -0.545592 -1.499812 -0.089958
23  1.411284  0.335008 -1.911956
24 -1.468716 -2.569037  0.896909
25 -0.584318  0.174206  3.028226
26  0.015619 -0.077268 -1.385655
27  1.191175  0.953772  0.354512
28  1.191991  0.095128 -0.590488
29 -1.118067  1.729722  1.204668
30  0.443431 -1.117314 -0.036582
31 -1.480004  1.247244 -0.109951
32 -0.514731  1.455674 -0.688065
33 -0.876742 -0.766922  0.209406
34  0.999265 -0.056820 -0.603960
35  1.218957 -0.437381 -0.101947
36  0.889065 -0.036806  1.267912
37 -1.579665 -1.544169 -1.413230
38 -0.941903  1.614733 -0.315585
39  0.547935  1.233692 -0.384419
40  0.972781  1.039949  1.543776
41 -0.825916  1.942681 -1.849283
42 -0.099794  0.170749 -1.288881
43  0.287042 -0.506104 -0.678657
44  0.441296 -0.099060  0.347198
45 -0.365115 -0.807221 -0.932193
46 -1.787543  1.222139 -0.935932
47 -0.338019 -2.027892  1.155308
48 -1.406451 -0.221610 -2.718018
49  0.494161  0.320213 -0.827758

In [106]:
k.replace(k.iloc[0],14)

            0          1          2
0   14.000000  14.000000  14.000000
1   -1.420991  14.000000   1.303350
2   14.000000  14.000000   0.304443
3    1.656585   1.599320   1.168198
4   -1.371662  14.000000  -0.563045
5   14.000000  14.000000  -1.687678
6    0.576487  -1.565742  -0.292461
7   -0.678988  14.000000  -0.843291
8   14.000000  14.000000   0.634397
9    0.021965   0.840554   1.662810
10  14.000000  14.000000  -0.598513
11  14.000000   2.867409   0.459316
12  14.000000   0.299162  -0.533026
13   0.077880   1.528570  -0.033770
14  14.000000  14.000000   0.685027
15   0.585727   0.056810  -0.824828
16   2.898903   0.925097   1.915837
17  -0.925602  -0.029634  -1.265946
18  -1.043710   0.032791  -0.360433
19  -1.270543   1.228248   0.124210
20   1.007473  -0.616905  -1.023697
21  -2.456578  -0.906363  -0.288901
22  -0.545592  -1.499812  -0.089958
23   1.411284   0.335008  -1.911956
24  -1.468716  -2.569037   0.896909
25  -0.584318   0.174206   3.028226
26   0.015619  -0.077268  -1.385655
27   1.191175   0.953772   0.354512
28   1.191991   0.095128  -0.590488
29  -1.118067   1.729722   1.204668
30   0.443431  -1.117314  -0.036582
31  -1.480004   1.247244  -0.109951
32  -0.514731   1.455674  -0.688065
33  -0.876742  -0.766922   0.209406
34   0.999265  -0.056820  -0.603960
35   1.218957  -0.437381  -0.101947
36   0.889065  -0.036806   1.267912
37  -1.579665  -1.544169  -1.413230
38  -0.941903   1.614733  -0.315585
39   0.547935   1.233692  -0.384419
40   0.972781   1.039949   1.543776
41  -0.825916   1.942681  -1.849283
42  -0.099794   0.170749  -1.288881
43   0.287042  -0.506104  -0.678657
44   0.441296  -0.099060   0.347198
45  -0.365115  -0.807221  -0.932193
46  -1.787543   1.222139  -0.935932
47  -0.338019  -2.027892   1.155308
48  -1.406451  -0.221610  -2.718018
49   0.494161   0.320213  -0.827758

In [107]:
k

            0          1         2
0   -0.707426   0.219924 -0.135498
1   -1.420991  14.000000  1.303350
2   14.000000  14.000000  0.304443
3    1.656585   1.599320  1.168198
4   -1.371662  14.000000 -0.563045
5   14.000000  14.000000 -1.687678
6    0.576487  -1.565742 -0.292461
7   -0.678988  14.000000 -0.843291
8   14.000000  14.000000  0.634397
9    0.021965   0.840554  1.662810
10  14.000000  14.000000 -0.598513
11  14.000000   2.867409  0.459316
12  14.000000   0.299162 -0.533026
13   0.077880   1.528570 -0.033770
14  14.000000  14.000000  0.685027
15   0.585727   0.056810 -0.824828
16   2.898903   0.925097  1.915837
17  -0.925602  -0.029634 -1.265946
18  -1.043710   0.032791 -0.360433
19  -1.270543   1.228248  0.124210
20   1.007473  -0.616905 -1.023697
21  -2.456578  -0.906363 -0.288901
22  -0.545592  -1.499812 -0.089958
23   1.411284   0.335008 -1.911956
24  -1.468716  -2.569037  0.896909
25  -0.584318   0.174206  3.028226
26   0.015619  -0.077268 -1.385655
27   1.191175   0.953772  0.354512
28   1.191991   0.095128 -0.590488
29  -1.118067   1.729722  1.204668
30   0.443431  -1.117314 -0.036582
31  -1.480004   1.247244 -0.109951
32  -0.514731   1.455674 -0.688065
33  -0.876742  -0.766922  0.209406
34   0.999265  -0.056820 -0.603960
35   1.218957  -0.437381 -0.101947
36   0.889065  -0.036806  1.267912
37  -1.579665  -1.544169 -1.413230
38  -0.941903   1.614733 -0.315585
39   0.547935   1.233692 -0.384419
40   0.972781   1.039949  1.543776
41  -0.825916   1.942681 -1.849283
42  -0.099794   0.170749 -1.288881
43   0.287042  -0.506104 -0.678657
44   0.441296  -0.099060  0.347198
45  -0.365115  -0.807221 -0.932193
46  -1.787543   1.222139 -0.935932
47  -0.338019  -2.027892  1.155308
48  -1.406451  -0.221610 -2.718018
49   0.494161   0.320213 -0.827758

In [122]:
k.T.drop_duplicates().T

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,-0.707426,-1.420991,14.000000,1.656585,-1.371662,14.000000,0.576487,-0.678988,14.000000,0.021965,...,0.972781,-0.825916,-0.099794,0.287042,0.441296,-0.365115,-1.787543,-0.338019,-1.406451,0.494161
1,0.219924,14.000000,14.000000,1.599320,14.000000,14.000000,-1.565742,14.000000,14.000000,0.840554,...,1.039949,1.942681,0.170749,-0.506104,-0.099060,-0.807221,1.222139,-2.027892,-0.221610,0.320213
2,-0.135498,1.303350,0.304443,1.168198,-0.563045,-1.687678,-0.292461,-0.843291,0.634397,1.662810,...,1.543776,-1.849283,-1.288881,-0.678657,0.347198,-0.932193,-0.935932,1.155308,-2.718018,-0.827758

In [124]:
pd.cut(k[0],5)

0     (-2.473, 0.835]
1     (-2.473, 0.835]
2      (10.709, 14.0]
3      (0.835, 4.126]
4     (-2.473, 0.835]
5      (10.709, 14.0]
6     (-2.473, 0.835]
7     (-2.473, 0.835]
8      (10.709, 14.0]
9     (-2.473, 0.835]
10     (10.709, 14.0]
11     (10.709, 14.0]
12     (10.709, 14.0]
13    (-2.473, 0.835]
14     (10.709, 14.0]
15    (-2.473, 0.835]
16     (0.835, 4.126]
17    (-2.473, 0.835]
18    (-2.473, 0.835]
19    (-2.473, 0.835]
20     (0.835, 4.126]
21    (-2.473, 0.835]
22    (-2.473, 0.835]
23     (0.835, 4.126]
24    (-2.473, 0.835]
25    (-2.473, 0.835]
26    (-2.473, 0.835]
27     (0.835, 4.126]
28     (0.835, 4.126]
29    (-2.473, 0.835]
30    (-2.473, 0.835]
31    (-2.473, 0.835]
32    (-2.473, 0.835]
33    (-2.473, 0.835]
34     (0.835, 4.126]
35     (0.835, 4.126]
36     (0.835, 4.126]
37    (-2.473, 0.835]
38    (-2.473, 0.835]
39    (-2.473, 0.835]
40     (0.835, 4.126]
41    (-2.473, 0.835]
42    (-2.473, 0.835]
43    (-2.473, 0.835]
44    (-2.473, 0.835]
45    (-2.473, 0.835]
46    (-2.473, 0.835]
47    (-2.473, 0.835]
48    (-2.473, 0.835]
49    (-2.473, 0.835]
Name: 0, dtype: category
Categories (5, interval[float64, right]): [(-2.473, 0.835] < (0.835, 4.126] < (4.126, 7.417] < (7.417, 10.709] < (10.709, 14.0]]